apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-database
  labels:
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      labels:
        type: database
    spec:
      containers:
        - name: sqldata        
          image: mcr.microsoft.com/mssql/server
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1433
          envFrom:
            - secretRef:
                name: database-secrets