apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

resources:
  - ../../base
  - database-deployment.yaml
  - database-service.yaml

secretGenerator:
  - name: microservice-secrets
    behavior: replace
    literals:
      - ConnectionStrings__DefaultConnection= Data source=weather-database,1433;Database=master;User Id=sa;Password=DEV_pass@word;

  - name: database-secrets
    literals:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DEV_pass@word
